### ISSUE TITLE
只有一张图片的时候  使用Glide 崩溃

### ISSUE THREAD

**Issue by mlp1995** [AlpsDog/Banner#9]
1.因为  Glide  中使用的 View的setTag  功能 用来保证 图片加载的时候 不会出现混乱  
当  这个View设置的tag  并不是Glide想要的类型的时候  Glide就会 跑出异常  

当图片只有  一张的时候  Banner  这个自定义VIew  给  ImageView 设置了一个 tag  将 Glide的tag 覆盖了  导致了崩溃 
建议  Banner的settag  使用   setTag(int key, final Object tag)  这个方法

**Comment by AlpsDog** [comment]
好的，老铁，感谢反馈！

**Comment by AlpsDog** [comment]
已修复，换成setId了，一开始考虑不周
